services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  PrestaShopBundle\Form\FormCloner: ~

  form.form_cloner:
    alias: PrestaShopBundle\Form\FormCloner
    public: true
    deprecated: ~

  form.form_builder_modifier:
    class: PrestaShopBundle\Form\FormBuilderModifier
    public: true
