services:
  PrestaShop\Module\PsxMarketingWithGoogle\Conversion\EnhancedConversionToggle:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Conversion\EnhancedConversionToggle
    public: true
    arguments:
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Adapter\ConfigurationAdapter'

  PrestaShop\Module\PsxMarketingWithGoogle\Conversion\UserDataProvider:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Conversion\UserDataProvider
    public: true
    arguments:
      - '@psxmarketingwithgoogle.customer'
      - '@psxmarketingwithgoogle.cart'
